### ISSUE TITLE
The preferences window doesn't fit properly in 1366 x 768 displays

### ISSUE THREAD

**Issue by P-dos-Santos** [FreeCAD/FreeCAD-Bundle#201] opened 2023-11-25 02:16 UTC
Hello folks. As described above, we have an issue with the preferences windows that cannot apply any new settings because the button to confirm them is hidden from the display. 

See the following images.

![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/16929155/5baa71f0-5ce8-4fe6-b2b2-a9bb2ecf825f)
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/16929155/0dc1e270-d187-4939-a2e9-776a15fd188b)

Thank you

**Comment by P-dos-Santos** [comment] 2023-11-25 02:19
```
OS: Fedora Linux 38 (KDE Plasma) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35176 (Git) AppImage
Build type: Release
Branch: main
Hash: dcd533af4bf0cb3dbc50c7d0e2fb579cad168819
Python 3.10.13, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: Portuguese/Brazil (pt_BR)
```

**Comment by JohnOCFII** [comment] 2023-11-25 03:37
Appears to be a duplicate of this (which has already been acknowledged as a known issue): https://github.com/FreeCAD/FreeCAD/issues/11004#issuecomment-1825880450

**Comment by amorfiniluigi82** [comment] 2023-11-25 13:27
Idem from from Linux AppImage.

![Schermata del 2023-11-25 14-25-09](https://github.com/FreeCAD/FreeCAD-Bundle/assets/123329788/1ee1612e-8c58-4dfe-9453-b97222454b59)


![Schermata del 2023-11-25 14-26-42](https://github.com/FreeCAD/FreeCAD-Bundle/assets/123329788/8015bd7f-3351-4603-8172-73f187680d66)

**Comment by chennes** [comment] 2023-11-25 18:12
This is not a Bundle issue. Closing in favor of FreeCAD#11511

**Closed** 2023-11-25 18:13 UTC
