### ISSUE TITLE
.AppImage is missing FreeCad Icon (no icon displayed when running)

### ISSUE THREAD

**Issue by AndKe** [FreeCAD/FreeCAD-Bundle#228] opened 2024-05-13 11:43 UTC
Please look to the open source project PrusaSlicer to see how to add the icon to AppImage, if in doubt.

**Comment by maxwxyz** [comment] 2024-05-28 15:33
@AndKe is still present in the current weekly?

**Comment by AndKe** [comment] 2024-05-28 17:13
@maxwxyz 
 I just tested FreeCAD_weekly-builds-37543-conda-Linux-x86_64-py311.AppImage 
The issue remains.

**Comment by adrianinsaval** [comment] 2024-05-28 18:27
What icon are we talking about?

**Comment by maxwxyz** [comment] 2024-05-28 18:46
I guess the weekly AppImage icon for the application

**Comment by AndKe** [comment] 2024-05-28 19:26
I am talking about the appicon in the "task area" when the application is running.
When FreeCad AppImage is running from an AppImage, then it is represented by a default "gear" icon.
When other AppImages run, they display their own icons.

**Comment by maxwxyz** [comment] 2024-05-28 19:35
A screenshot would help but I guess you mean that how it is on my Windows:
![grafik](https://github.com/FreeCAD/FreeCAD-Bundle/assets/6246609/56d1f096-ab4c-430b-a7ba-d9aecdc434b0)

**Comment by AndKe** [comment] 2024-05-28 21:06
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/1468842/0d031562-b0f1-40e4-840f-72e07f8d7f9a)

A part of the vertical "taskbar/Shortcut" bar on Ubuntu  (apps with a orange dot are running)
you see a PDF reader, then PrusaSlicer , then FreeCad (the gear icon)  - it's default for iconless-apps.

**Comment by adrianinsaval** [comment] 2024-05-29 03:16
what's your system and are you running wayland or x11? If this is wayland, sorry this is a limitation of wayland and there's nothing we can do when shipping as an appimage. You can create a org.freecad.FreeCAD.destop file with the correct icon info at .local/share/applications and copy the icon to .local/share/icons to workaround this.

**Comment by AndKe** [comment] 2024-05-29 06:11
I am using x11 (mostly due to xdotools) 
I do already have a .desktop icon, (which works for the shortcut to the app(which has an icon) - but does not help once the app is started)
but unlike (for example) PrusaSlicer AppImage, FreeCAD 's appimage is missing the necessary information to make it display it's own icon when running.

**Comment by AndKe** [comment] 2024-05-29 06:20
Also: your post above me helped me because I discovered that when moving the icon to ~/.local/share/icons
, and using just a filename in the deskop file, Icon=FreeCAD.png (rather than full path to other location)   works fine.
BTW: The behavior is the same for x11 and Wayland, both works now.
The main difference is still:  Other .AppImage files dispålay their icon instantly (on both desktop managers) , but FreeCAD AppImage does not.   
Please make it work :)

**Comment by adrianinsaval** [comment] 2024-05-29 06:21
huh, that's weird I never experienced this in x11

**Comment by adrianinsaval** [comment] 2024-07-05 22:00
I cannot reproduce this problem, I can only assume it is an issue on your system. Please let me know if this can be reproduced on a clean system on x11, otherwise I'll close this issue

**Comment by jose1968us** [comment] 2024-07-21 09:56
If you check the .desktop file that is in the /tmp/.mount_freecad file generated when running freecad you will see that the reference to the icon is missing the file extension (.svg)

**Comment by adrianinsaval** [comment] 2024-08-13 00:11
> If you check the .desktop file that is in the /tmp/.mount_freecad file generated when running freecad you will see that the reference to the icon is missing the file extension (.svg)

this should not be a problem, consider reporting this bug to your DE instead

**Closed** 2024-09-28 03:46 UTC
