### ISSUE TITLE
[Problem] Mac build is corrupt (39100, Nov. 3)

### ISSUE THREAD

**Issue by Stokestack** [FreeCAD/FreeCAD-Bundle#329] opened 2024-11-03 21:00 UTC
**Describe the bug**
Mac OS displays a dialog saying that FreeCAD is "damaged" upon launch.

**To Reproduce**
Download and install https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-39100-conda-macOS-arm64-py311.dmg

Launch FreeCAD from its icon or by double-clicking on an existing file.

**Screenshots**
Attached.

**Additional context**
I re-downloaded the DMG and got the same result.
<img width="372" alt="damaged" src="https://github.com/user-attachments/assets/d3301115-561b-4454-9756-c984ff757b31">

**Comment by oursland** [comment] 2024-11-03 22:46
@Stokestack The weekly builds are not signed.  To run them you will need to run `xattr -c /Applications/FreeCAD.app` to remove the quarantine attribute associated with applications downloaded from the internet.

**Comment by Stokestack** [comment] 2024-11-03 23:40
Thanks, but that's not the reported problem. Unsigned apps result in a "This application can't be checked for..." or words to that effect.

**Comment by oursland** [comment] 2024-11-04 00:15
The behavior changed in macOS 15.  Universal and Apple Silicon applications no longer permit running unsigned with the quarantine attribute.  Unsigned Intel applications will provide the popup you're more familiar with.

**Comment by Stokestack** [comment] 2024-11-04 01:28
Interesting. I've seen the "can't be checked" message under OS 15. I'll file a bug report with Apple, because this behavior is wrong.

**Comment by nicolasgalvez** [comment] 2024-11-04 17:58
> @Stokestack The weekly builds are not signed. To run them you will need to run `xattr -c /Applications/FreeCAD.app` to remove the quarantine attribute associated with applications downloaded from the internet.

Thanks! Works for me.

> Interesting. I've seen the "can't be checked" message under OS 15. I'll file a bug report with Apple, because this behavior is wrong.

Thanks for filing a report, LMK if you want me to +1 it or whatever. That's weird behavior.

**Comment by Stokestack** [comment] 2024-11-04 19:23
Filed report FB15674712 with Apple, entitled _Unsigned applications are erroneously reported as "damaged."_

I will say, though that there is [something wrong with the current weekly build](https://github.com/FreeCAD/FreeCAD/issues/17658); although I doubt the message has anything to do with that.

**Comment by adrianinsaval** [comment] 2024-11-13 11:25
duplicate of #291

**Closed by adrianinsaval** 2024-11-13 11:25 UTC
