### ISSUE TITLE
Appimage not signed

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD-Bundle#134] opened 2022-09-10 00:01 UTC
I am upgrading the Freecad Weekly with the Appimage upgrade tool.

Last week I did not have this issue. 

![image](https://user-images.githubusercontent.com/1277920/189460261-cc84d5f6-5829-4631-b5f4-2c5ae6f5ea08.png)

**Comment by luzpaz** [comment] 2022-09-10 16:22
Related #6

**Comment by adrianinsaval** [comment] 2022-10-04 12:08
> Last week I did not have this issue.

that's strange, AFAIK the appimage never got signed.

**Comment by leoheck** [comment] 2022-10-04 14:09
Exactly what I thought. But at that time, the installation did not complained and the progress bar turned green instead of yellow. Maybe it was a different version of the updater tool then. Unfortunately I cannot check this anymore. I can only get the current version I am using.

**Comment by adrianinsaval** [comment] 2024-08-27 15:43
duplicate of #6 and this should be solved for x86_64 now

**Closed by adrianinsaval** 2024-08-27 15:43 UTC
