### ISSUE TITLE
[Bug] PartDesign Thickness Feature not working

### ISSUE THREAD

**Issue by BloodyRain2k** [FreeCAD/FreeCAD-Bundle#74] opened 2021-07-02 13:49 UTC
I managed to construct a seemingly too complex structure for FreeCAD to turn into a pipe.
![image](https://user-images.githubusercontent.com/1014362/124283519-48c80e80-db4c-11eb-8f23-a6b5170aee28.png)
It's just a circle made up of 2 half-circles, because I thought it would actually help FreeCAD, if the seam-line that results even from pure circles would be symmetric on both sides, but it didn't.
The other side is just a rounded rectangle with filleted corners.

The only time I got the whole thing to return a pipe was when the rectangle was sharp edged.
But that then left me with the problem of not being able to round the corners with the fillet feature...

I tried this with various versions of FreeCAD, including the latest weekly. None managed to get this to work.

```
OS: Windows 7 SP 1 (6.1)
Word size of FreeCAD: 64-bit
Version: 0.20.25157 (Git)
Build type: Release
Branch: master
Hash: 257cdd8f423f1530b8df6f53e242de629fee4e85
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: English/United States (en_US)
```

[AC_Water_Adapter.zip](https://github.com/FreeCAD/FreeCAD-Bundle/files/6754987/AC_Water_Adapter.zip)

**Comment by luzpaz** [comment] 2021-07-02 18:05
This is not a bugtracker for FreeCAD. It's a packaging repository. Thickness bugs are a known issue. Seach https://tracker.freecadweb.org/ for `thickness` and you'll see all open bugs. Feel free to open a forum.freecadweb.org thread about it.

Closing ticket

**Closed by luzpaz** 2021-07-02 18:05 UTC
